# kustomize/overlays/asia-southeast1/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: asia-southeast1-
resources:
- ../../base
patches:
- path: patch.yaml
