---
# ServiceImport for us-east5 cluster's broadcaster service
apiVersion: net.gke.io/v1
kind: ServiceImport
metadata:
  name: us-east5-broadcaster-headless
  annotations:
    net.gke.io/cluster-dns: "us-east5-broadcaster-headless.default.svc.clusterset.local"
spec:
  ports:
  - port: 4000
    protocol: TCP
  type: ClusterSetIP
  sessionAffinity: None
---
# ServiceImport for europe-west9 cluster's broadcaster service
apiVersion: net.gke.io/v1
kind: ServiceImport
metadata:
  name: europe-west9-broadcaster-headless
  annotations:
    net.gke.io/cluster-dns: "europe-west9-broadcaster-headless.default.svc.clusterset.local"
spec:
  ports:
  - port: 4000
    protocol: TCP
  type: ClusterSetIP
  sessionAffinity: None 