apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base configuration

# Add a prefix to all resource names to ensure they are unique per cluster
# e.g., the 'broadcaster' StatefulSet becomes 'us-east5-broadcaster'
namePrefix: us-east5-

# Apply patches to the base configuration
resources:
- ../../base
# Import ServiceImports for remote clusters only (not own cluster)
- serviceimports.yaml
patches:
- path: patch.yaml

# Replace PROJECT_ID placeholder with actual project ID
replacements:
- source:
    kind: ConfigMap
    name: project-info
    fieldPath: data.PROJECT_ID
  targets:
  - select:
      kind: SecretProviderClass
      name: broadcaster-secrets
    fieldPaths:
    - spec.parameters.secrets
  - select:
      kind: ServiceAccount
      name: broadcaster-sa
    fieldPaths:
    - metadata.annotations.[iam.gke.io/gcp-service-account]
