apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base configuration
bases:
  - ../../base

# Add a prefix to all resource names to ensure they are unique per cluster
# e.g., the 'broadcaster' StatefulSet becomes 'us-east5-broadcaster'
namePrefix: us-east5-

# Apply patches to the base configuration
patchesStrategicMerge:
  - patch.yaml 