apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broadcaster
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: PHX_HOST
              value: "us-east5.broadcaster.gcp.example.com"
            - name: ICE_SERVER_URL
              value: "turn:us-east5.turn.gcp.example.com:3478?transport=udp" 