apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broadcaster
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: PHX_HOST
              value: "us-east5.broadcaster.gcp.example.com"
            - name: ICE_SERVER_URL
              value: "turn:us-east5.turn.gcp.example.com:3478?transport=udp" 
            - name: CLUSTER_REGION
              value: "us-east5"
            - name: K8S_SERVICE_NAME
              value: "us-east5-broadcaster-headless"
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: us-east5-broadcaster-secrets 