# kustomize/overlays/europe-west9/patch.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broadcaster
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: PHX_HOST
              value: "europe-west9.broadcaster.gcp.example.com"
            - name: ICE_SERVER_URL
              value: "turn:europe-west9.turn.gcp.example.com:3478?transport=udp" 
            - name: CLUSTER_REGION
              value: "europe-west9"
            - name: K8S_SERVICE_NAME
              value: "europe-west9-broadcaster-headless"
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: europe-west9-broadcaster-secrets 