apiVersion: apps/v1
kind: StatefulSet
metadata:
  # The name will be patched by Kustomize overlays
  name: broadcaster
spec:
  #replicas: 3
  serviceName: broadcaster-headless
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      serviceAccountName: broadcaster-sa
      containers:
        - name: broadcaster
          # This image will be patched by Kustomize
          image: ghcr.io/l7mp/multicluster-broadcaster-swm-l7mp/k8s_broadcaster
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DISTRIBUTION_MODE
              value: k8s
            - name: K8S_SERVICE_NAME
              value: broadcaster-headless
            # Erlang Distribution cookie for cross-cluster authentication
            - name: ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: erlang-cookie
            # These values will be patched by Kustomize overlays
            - name: ICE_SERVER_URL
              value: "turn:turn.example.com:3478?transport=udp"
            - name: PHX_HOST
              value: "broadcaster.brianeft.com"
            # --- Static config below ---
            - name: ICE_SERVER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: ice-server-username
            - name: ICE_SERVER_CREDENTIAL
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: ice-server-credential
            - name: ICE_TRANSPORT_POLICY
              value: "relay"
            - name: ICE_PORT_RANGE
              value: "51000-52000"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: secret-key-base
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: admin-username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: admin-password
            - name: WHIP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: whip-token
            - name: CHECK_ORIGIN
              value: "false"
            # Cluster info for UI buttons (consistent across all regions)
            - name: C0
              value: "GLOBAL;broadcaster.brianeft.com;0;0"
            - name: C1
              value: "us-east5;broadcaster.brianeft.com;40.7128;-74.0060"
            - name: C2
              value: "europe-west9;broadcaster.brianeft.com;50.1109;8.6821"
            - name: C3
              value: "asia-southeast1;broadcaster.brianeft.com;1.3521;103.8198"
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: broadcaster-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: broadcaster-headless
spec:
  selector:
    app: broadcaster
  type: ClusterIP
  clusterIP: None
---
# This manifest exports the broadcaster-headless service to other clusters in the GKE Fleet.
# This replaces the Cilium service annotations.
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: broadcaster-headless
spec:
  # No spec fields are required. The presence of the object is enough.
---
apiVersion: v1
kind: Service
metadata:
  name: broadcaster
  labels:
    app: broadcaster
spec:
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: broadcaster
  type: ClusterIP