apiVersion: apps/v1
kind: StatefulSet
metadata:
  # The name will be patched by Kustomize overlays
  name: broadcaster
spec:
  #replicas: 3
  serviceName: broadcaster-headless
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          # This image will be patched by Kustomize
          image: ghcr.io/l7mp/multicluster-broadcaster-swm-l7mp/k8s_broadcaster
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DISTRIBUTION_MODE
              value: k8s
            - name: K8S_SERVICE_NAME
              value: broadcaster-headless
            # Erlang Distribution cookie for cross-cluster authentication
            - name: ERLANG_COOKIE
              value: "multicluster-broadcaster-cookie-gcp-2025"
            # These values will be patched by Kustomize overlays
            - name: ICE_SERVER_URL
              value: "turn:turn.example.com:3478?transport=udp"
            - name: PHX_HOST
              value: "app.example.com"
            # --- Static config below ---
            - name: ICE_SERVER_USERNAME
              value: "user-1"
            - name: ICE_SERVER_CREDENTIAL
              value: "pass-1"
            - name: ICE_TRANSPORT_POLICY
              value: "relay"
            - name: ICE_PORT_RANGE
              value: "51000-52000"
            - name: SECRET_KEY_BASE
              value: "u1gYGbDNgA5RwdKGFe9CdK+5qLCVROAHZAFPgUVlcmjTEGdvpXqgYW9qFjLQvxZO"
            - name: ADMIN_USERNAME
              value: "admin"
            - name: ADMIN_PASSWORD
              value: "admin"
            - name: WHIP_TOKEN
              value: "token"
            - name: CHECK_ORIGIN
              value: "false"
            # Cluster info for UI buttons (consistent across all regions)
            - name: C0
              value: "GLOBAL;global.broadcaster.gcp.example.com;0;0"
            - name: C1
              value: "us-east5;us-east5.broadcaster.gcp.example.com;40.7128;-74.0060"
            - name: C2
              value: "europe-west9;europe-west9.broadcaster.gcp.example.com;50.1109;8.6821"
            - name: C3
              value: "asia-southeast1;asia-southeast1.broadcaster.gcp.example.com;1.3521;103.8198"
---
apiVersion: v1
kind: Service
metadata:
  name: broadcaster-headless
spec:
  selector:
    app: broadcaster
  type: ClusterIP
  clusterIP: None
---
# This manifest exports the broadcaster-headless service to other clusters in the GKE Fleet.
# This replaces the Cilium service annotations.
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: broadcaster-headless
spec:
  # No spec fields are required. The presence of the object is enough.
---
apiVersion: v1
kind: Service
metadata:
  name: broadcaster
  labels:
    app: broadcaster
spec:
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: broadcaster
  type: ClusterIP