apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: broadcaster-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/PROJECT_ID/secrets/broadcaster-erlang-cookie/versions/latest"
        path: "erlang-cookie"
      - resourceName: "projects/PROJECT_ID/secrets/broadcaster-secret-key-base/versions/latest"
        path: "secret-key-base"
      - resourceName: "projects/PROJECT_ID/secrets/broadcaster-admin-username/versions/latest"
        path: "admin-username"
      - resourceName: "projects/PROJECT_ID/secrets/broadcaster-admin-password/versions/latest"
        path: "admin-password"
      - resourceName: "projects/PROJECT_ID/secrets/broadcaster-whip-token/versions/latest"
        path: "whip-token"
      - resourceName: "projects/PROJECT_ID/secrets/broadcaster-ice-server-username/versions/latest"
        path: "ice-server-username"
      - resourceName: "projects/PROJECT_ID/secrets/broadcaster-ice-server-credential/versions/latest"
        path: "ice-server-credential"
  # Optional: Create Kubernetes secrets from the mounted secrets
  secretObjects:
  - data:
    - key: erlang-cookie
      objectName: erlang-cookie
    - key: secret-key-base
      objectName: secret-key-base
    - key: admin-username
      objectName: admin-username
    - key: admin-password
      objectName: admin-password
    - key: whip-token
      objectName: whip-token
    - key: ice-server-username
      objectName: ice-server-username
    - key: ice-server-credential
      objectName: ice-server-credential
    secretName: broadcaster-secrets
    type: Opaque 