apiVersion: v1
kind: ServiceAccount
metadata:
  name: broadcaster-sa
  annotations:
    # This annotation will be patched by Kustomize with the actual service account email
    iam.gke.io/gcp-service-account: "broadcaster-secrets-sa@PROJECT_ID.iam.gserviceaccount.com" 